# Generated by Django 4.2.13 on 2024-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_code', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.SmallIntegerField()),
                ('country', models.CharField()),
                ('phone_number', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('immediate_contact', models.CharField()),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
    ]
