# Generated by Django 4.2.13 on 2024-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_class_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_empty_slots',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number_of_chairs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number_of_desks',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number_of_tvs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_white_boards',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
