# Generated by Django 4.2.13 on 2024-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
